### ISSUE TITLE
Guide on Hosting on Production

### ISSUE THREAD

**Issue by shirshak55** [brson/basic-http-server#28]
Is there any guide how to host this in production?

**Comment by shirshak55** [comment]
And for education purpose it would be easy to release binary so production server don't have to use rust. We can do cross compile to ubuntu/RHEL/debian ?

**Comment by CoolOppo** [comment]
Literally in the readme:

**Note that basic-http-server is not production-ready and should not be exposed to the internet. It is a learning and development tool.**

**Comment by shirshak55** [comment]
@CoolOppo the point is learning to host binaries not doing production work u think :)

**Comment by vi** [comment]
What exactly can go wrong if basic-http-server running without `-x` is exposed?
Are there specific problems that need to be resolved prior considering basic (staticfile-only) usage of basic-http-server production-ready?

**Comment by shirshak55** [comment]
I am closing this issue. 

@vi there may be security issues like directory traversal etc.

The best way is to use systemd and make daemon to host it on production.
